site:
  name: Restorative Bodywork
  site: 'https://restorativebodyworkatx.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: kmkHW_W3a6t9LZdK_e208kkR_bkQx-ZUYQ5zUIbyfHc

# Default SEO metadata
metadata:
  title:
    default: Restorative Bodywork
    template: '%s — Restorative Bodywork'
  description: 'Restorative Bodywork, South Austin based therapists offering therapeutic massages to enhance your overall health and vitality.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Restorative Bodywork
    images:
      - url: '~/assets/images/closeups/hands-back1.jpeg'
        width: 1200
        height: 628
        alt: 'Restorative Bodywork - Therapeutic Massage in Austin'
    type: website
    locale: en_US
  # twitter:
  #   cardType: summary_large_image
  #   site: '@restorativebodyworkatx'
  #   creator: '@restorativebodyworkatx'
  #   handle: '@restorativebodyworkatx'

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(16 16 16)
        heading: rgb(0 0 0)
        muted: rgb(40 40 40)
        bgPage: rgb(255 255 255)
        primary: rgb(0 124 220)
        secondary: rgb(30 58 138)
        accent: rgb(109 40 217)
        info: rgb(119 182 234)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
    dark:
      fonts: {}
      colors:
        default: rgb(247, 248, 248)
        heading: rgb(247, 248, 248)
        muted: rgb(200, 188, 208)
        bgPage: rgb(237 244 237)
        primary: rgb(121 183 145)
        secondary: rgb(30 58 138)
        accent: rgb(135 77 2267)
        info: rgb(58 191 248)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
